@startuml
!include ./includes/C4_Container.puml
!include ./includes/C4_Component.puml
Person(HomeUser, "Житель Дома", "Использует систему для контроля температуры")

System_Boundary(HeatingSystem, "Система Управления Smart-Home"){
    Container(HeatingWebApp, "Веб Приложение", "React", "Интерфейс для пользователей (мобильный / десктоп)")
    
    Container_Boundary(Backend, "Сервер Устройств") {
        Container(UserAuth, "Аутентификация", "Аутентификация пользователей")
            Container(Monitor, "Мониторинг")
            Container(Devices, "Устройства", "Управление устройствами")
    }
}

Container(CloudService, "Внешний сервис датчиков температуры и реле отопления", "", "")
        
Rel(HomeUser, HeatingWebApp, "Управляет устройствами, Получает данные устройств", "HTTPS")
Rel(HeatingWebApp, Monitor, "Данные устройств", "Websockets/HTTPS")
Rel(HeatingWebApp, UserAuth, "Аутентификация пользователей, токен JWT", "HTTPS")
Rel(HeatingWebApp, Devices, "Управление устройствами", "HTTPS, REST API")
Rel(Monitor, UserAuth, "Авторизация пользователей, токен JWT", "HTTPS, REST API")
Rel(Devices, UserAuth, "Авторизация пользователей, токен JWT", "HTTPS, REST API")
Rel(Monitor, CloudService, "Получение данных от устройств")
Rel(Devices, CloudService, "Команды на устройства")
@enduml