@startuml
!include ./includes/C4_Container.puml
!include ./includes/C4_Component.puml
System_Boundary(HeatingSystem, "Система Управления Отоплением smart-home") {
    Container_Boundary(HeatingServer, "Сервер Отопления") {
        Component(HeatingLogic, "Бекенд приложения отопления", "Go", "REST API управления отоплением")
    }
    ContainerDb(HeatingDatabase, "База Данных Отопления", "Postgres", "Хранит все данные системы")
    Container(HeatingWebApp, "Веб Приложение", "React", "Интерфейс для пользователей")    
}
Person(HomeUser, "Житель Дома", "Использует систему для контроля температуры")
Container(CloudService, "Внешний сервис датчиков температуры и реле отопления", "", "")
Rel(HomeUser, HeatingWebApp, "Мониторит температуру", "HTTPS")
Rel(HomeUser, HeatingWebApp, "Вкл/выкл отопление", "HTTPS")
Rel(HeatingLogic, HeatingDatabase, "Получение и сохранение данных")
Rel(HeatingServer, CloudService, "Получение данных о температуре")
Rel(HeatingServer, CloudService, "Команды на включение/выключение отопления")
Rel(HeatingWebApp, HeatingServer, "Команды управления и получение данных", "REST API")
@enduml